version: '3.8'

x-common-variables: &common-variables
  #MYSQL_DATABASE: books

services:
  ethtps.api:
    restart: always
    image: ${DOCKER_REGISTRY-}ethtpsapi
    expose:
      - "6430"
    ports:
      - "6430:6430"
    build:
      context: .
      dockerfile: ETHTPS.API/Dockerfile


  ethtps.frontend:
    depends_on:
      - ethtps.api
    restart: always
    image: ${DOCKER_REGISTRY-}ethtpsfrontend
    expose:
      - "3006"
    ports:
      - "3006:3006"
    build:
      context: .
      dockerfile: React/ethtps.frontend/Dockerfile