/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* Feature service.
* @module api/FeatureApi
* @version 1.0
*/
export default class FeatureApi {

    /**
    * Constructs a new FeatureApi. 
    * @alias module:api/FeatureApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiStatusGetFeaturesGet operation.
     * @callback module:api/FeatureApi~apiStatusGetFeaturesGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.featureId 
     * @param {String} opts.featureName 
     * @param {String} opts.project 
     * @param {module:api/FeatureApi~apiStatusGetFeaturesGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiStatusGetFeaturesGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'FeatureId': opts['featureId'],
        'FeatureName': opts['featureName'],
        'Project': opts['project']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/Status/GetFeatures', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiStatusIsFeatureEnabledGet operation.
     * @callback module:api/FeatureApi~apiStatusIsFeatureEnabledGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.featureId 
     * @param {String} opts.featureName 
     * @param {String} opts.project 
     * @param {module:api/FeatureApi~apiStatusIsFeatureEnabledGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiStatusIsFeatureEnabledGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'FeatureId': opts['featureId'],
        'FeatureName': opts['featureName'],
        'Project': opts['project']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/Status/IsFeatureEnabled', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
