/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.info API
 * Backend definition for ethtps.info; you\'re free to play around
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  APIKeyResponseModel,
} from '../models';
import {
    APIKeyResponseModelFromJSON,
    APIKeyResponseModelToJSON,
} from '../models';

export interface ApiV3APIKeysRegisterNewKeyForProofGetNewKeyGetRequest {
    humanityProof?: string;
}

/**
 * 
 */
export class APIKeyApi extends runtime.BaseAPI {

    /**
     */
    async apiV3APIKeysRegisterNewKeyForProofGetNewKeyGetRaw(requestParameters: ApiV3APIKeysRegisterNewKeyForProofGetNewKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APIKeyResponseModel>> {
        const queryParameters: any = {};

        if (requestParameters.humanityProof !== undefined) {
            queryParameters['humanityProof'] = requestParameters.humanityProof;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v3/APIKeys/RegisterNewKeyForProof/GetNewKey`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APIKeyResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async apiV3APIKeysRegisterNewKeyForProofGetNewKeyGet(requestParameters: ApiV3APIKeysRegisterNewKeyForProofGetNewKeyGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APIKeyResponseModel> {
        const response = await this.apiV3APIKeysRegisterNewKeyForProofGetNewKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
