/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.info API
 * Backend definition for ethtps.info; you\'re free to play around
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DataPoint,
  DataResponseModel,
  TimeInterval,
} from '../models';
import {
    DataPointFromJSON,
    DataPointToJSON,
    DataResponseModelFromJSON,
    DataResponseModelToJSON,
    TimeIntervalFromJSON,
    TimeIntervalToJSON,
} from '../models';

export interface ApiV2GasAdjustedTPSGetGetRequest {
    xAPIKey?: string;
    provider?: string;
    network?: string;
    includeSidechains?: boolean;
    interval?: TimeInterval;
}

export interface ApiV2GasAdjustedTPSGetMonthlyDataByYearGetRequest {
    xAPIKey?: string;
    provider?: string;
    network?: string;
    includeSidechains?: boolean;
    year?: number;
}

export interface ApiV2GasAdjustedTPSInstantGetRequest {
    xAPIKey?: string;
    provider?: string;
    network?: string;
    includeSidechains?: boolean;
}

export interface ApiV2GasAdjustedTPSMaxGetRequest {
    xAPIKey?: string;
    provider?: string;
    network?: string;
    includeSidechains?: boolean;
}

/**
 * 
 */
export class GasAdjustedTPSApi extends runtime.BaseAPI {

    /**
     */
    async apiV2GasAdjustedTPSGetGetRaw(requestParameters: ApiV2GasAdjustedTPSGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<DataResponseModel>; }>> {
        const queryParameters: any = {};

        if (requestParameters.provider !== undefined) {
            queryParameters['Provider'] = requestParameters.provider;
        }

        if (requestParameters.network !== undefined) {
            queryParameters['Network'] = requestParameters.network;
        }

        if (requestParameters.includeSidechains !== undefined) {
            queryParameters['IncludeSidechains'] = requestParameters.includeSidechains;
        }

        if (requestParameters.interval !== undefined) {
            queryParameters['interval'] = requestParameters.interval;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xAPIKey !== undefined && requestParameters.xAPIKey !== null) {
            headerParameters['X-API-Key'] = String(requestParameters.xAPIKey);
        }

        const response = await this.request({
            path: `/api/v2/GasAdjustedTPS/Get`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiV2GasAdjustedTPSGetGet(requestParameters: ApiV2GasAdjustedTPSGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<DataResponseModel>; }> {
        const response = await this.apiV2GasAdjustedTPSGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV2GasAdjustedTPSGetMonthlyDataByYearGetRaw(requestParameters: ApiV2GasAdjustedTPSGetMonthlyDataByYearGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<DataResponseModel>; }>> {
        const queryParameters: any = {};

        if (requestParameters.provider !== undefined) {
            queryParameters['Provider'] = requestParameters.provider;
        }

        if (requestParameters.network !== undefined) {
            queryParameters['Network'] = requestParameters.network;
        }

        if (requestParameters.includeSidechains !== undefined) {
            queryParameters['IncludeSidechains'] = requestParameters.includeSidechains;
        }

        if (requestParameters.year !== undefined) {
            queryParameters['year'] = requestParameters.year;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xAPIKey !== undefined && requestParameters.xAPIKey !== null) {
            headerParameters['X-API-Key'] = String(requestParameters.xAPIKey);
        }

        const response = await this.request({
            path: `/api/v2/GasAdjustedTPS/GetMonthlyDataByYear`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiV2GasAdjustedTPSGetMonthlyDataByYearGet(requestParameters: ApiV2GasAdjustedTPSGetMonthlyDataByYearGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<DataResponseModel>; }> {
        const response = await this.apiV2GasAdjustedTPSGetMonthlyDataByYearGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV2GasAdjustedTPSInstantGetRaw(requestParameters: ApiV2GasAdjustedTPSInstantGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<DataPoint>; }>> {
        const queryParameters: any = {};

        if (requestParameters.provider !== undefined) {
            queryParameters['Provider'] = requestParameters.provider;
        }

        if (requestParameters.network !== undefined) {
            queryParameters['Network'] = requestParameters.network;
        }

        if (requestParameters.includeSidechains !== undefined) {
            queryParameters['IncludeSidechains'] = requestParameters.includeSidechains;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xAPIKey !== undefined && requestParameters.xAPIKey !== null) {
            headerParameters['X-API-Key'] = String(requestParameters.xAPIKey);
        }

        const response = await this.request({
            path: `/api/v2/GasAdjustedTPS/Instant`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiV2GasAdjustedTPSInstantGet(requestParameters: ApiV2GasAdjustedTPSInstantGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<DataPoint>; }> {
        const response = await this.apiV2GasAdjustedTPSInstantGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV2GasAdjustedTPSMaxGetRaw(requestParameters: ApiV2GasAdjustedTPSMaxGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: DataPoint; }>> {
        const queryParameters: any = {};

        if (requestParameters.provider !== undefined) {
            queryParameters['Provider'] = requestParameters.provider;
        }

        if (requestParameters.network !== undefined) {
            queryParameters['Network'] = requestParameters.network;
        }

        if (requestParameters.includeSidechains !== undefined) {
            queryParameters['IncludeSidechains'] = requestParameters.includeSidechains;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xAPIKey !== undefined && requestParameters.xAPIKey !== null) {
            headerParameters['X-API-Key'] = String(requestParameters.xAPIKey);
        }

        const response = await this.request({
            path: `/api/v2/GasAdjustedTPS/Max`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, DataPointFromJSON));
    }

    /**
     */
    async apiV2GasAdjustedTPSMaxGet(requestParameters: ApiV2GasAdjustedTPSMaxGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: DataPoint; }> {
        const response = await this.apiV2GasAdjustedTPSMaxGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
