/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EthtpsApi);
  }
}(this, function(expect, EthtpsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EthtpsApi.GeneralApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GeneralApi', function() {
    describe('aPIV2ColorDictionaryGet', function() {
      it('should call aPIV2ColorDictionaryGet successfully', function(done) {
        //uncomment below and update the code to test aPIV2ColorDictionaryGet
        //instance.aPIV2ColorDictionaryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('aPIV2IntervalsGet', function() {
      it('should call aPIV2IntervalsGet successfully', function(done) {
        //uncomment below and update the code to test aPIV2IntervalsGet
        //instance.aPIV2IntervalsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('aPIV2NetworksGet', function() {
      it('should call aPIV2NetworksGet successfully', function(done) {
        //uncomment below and update the code to test aPIV2NetworksGet
        //instance.aPIV2NetworksGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('aPIV2ProviderTypesColorDictionaryGet', function() {
      it('should call aPIV2ProviderTypesColorDictionaryGet successfully', function(done) {
        //uncomment below and update the code to test aPIV2ProviderTypesColorDictionaryGet
        //instance.aPIV2ProviderTypesColorDictionaryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('aPIV2ProvidersGet', function() {
      it('should call aPIV2ProvidersGet successfully', function(done) {
        //uncomment below and update the code to test aPIV2ProvidersGet
        //instance.aPIV2ProvidersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
