/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChartData } from "./ChartData"
import { ProviderResponseModel } from "./ProviderResponseModel"

export class HomePageResponseModel {
  "chartData"?: ChartData
  "maxData"?: { [key: string]: any }
  "instantData"?: { [key: string]: any }
  "colorDictionary"?: { [key: string]: string }
  "providerTypesColorDictionary"?: { [key: string]: string }
  "providers"?: Array<ProviderResponseModel>

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "chartData",
      baseName: "chartData",
      type: "ChartData",
      format: "",
    },
    {
      name: "maxData",
      baseName: "maxData",
      type: "{ [key: string]: any; }",
      format: "",
    },
    {
      name: "instantData",
      baseName: "instantData",
      type: "{ [key: string]: any; }",
      format: "",
    },
    {
      name: "colorDictionary",
      baseName: "colorDictionary",
      type: "{ [key: string]: string; }",
      format: "",
    },
    {
      name: "providerTypesColorDictionary",
      baseName: "providerTypesColorDictionary",
      type: "{ [key: string]: string; }",
      format: "",
    },
    {
      name: "providers",
      baseName: "providers",
      type: "Array<ProviderResponseModel>",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return HomePageResponseModel.attributeTypeMap
  }
}
