/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DataResponseModel from './DataResponseModel';
import ProviderModel from './ProviderModel';

/**
 * The AllDataModel model module.
 * @module model/AllDataModel
 * @version 1.0
 */
class AllDataModel {
    /**
     * Constructs a new <code>AllDataModel</code>.
     * @alias module:model/AllDataModel
     */
    constructor() { 
        
        AllDataModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AllDataModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AllDataModel} obj Optional instance to populate.
     * @return {module:model/AllDataModel} The populated <code>AllDataModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AllDataModel();

            if (data.hasOwnProperty('providers')) {
                obj['providers'] = ApiClient.convertToType(data['providers'], [ProviderModel]);
            }
            if (data.hasOwnProperty('maxData')) {
                obj['maxData'] = ApiClient.convertToType(data['maxData'], {'String': Object});
            }
            if (data.hasOwnProperty('allTPSData')) {
                obj['allTPSData'] = ApiClient.convertToType(data['allTPSData'], {'String': {'String': [DataResponseModel]}});
            }
            if (data.hasOwnProperty('allGPSData')) {
                obj['allGPSData'] = ApiClient.convertToType(data['allGPSData'], {'String': {'String': [DataResponseModel]}});
            }
            if (data.hasOwnProperty('allGasAdjustedTPSData')) {
                obj['allGasAdjustedTPSData'] = ApiClient.convertToType(data['allGasAdjustedTPSData'], {'String': {'String': [DataResponseModel]}});
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ProviderModel>} providers
 */
AllDataModel.prototype['providers'] = undefined;

/**
 * @member {Object.<String, Object>} maxData
 */
AllDataModel.prototype['maxData'] = undefined;

/**
 * @member {Object.<String, Object.<String, Array.<module:model/DataResponseModel>>>} allTPSData
 */
AllDataModel.prototype['allTPSData'] = undefined;

/**
 * @member {Object.<String, Object.<String, Array.<module:model/DataResponseModel>>>} allGPSData
 */
AllDataModel.prototype['allGPSData'] = undefined;

/**
 * @member {Object.<String, Object.<String, Array.<module:model/DataResponseModel>>>} allGasAdjustedTPSData
 */
AllDataModel.prototype['allGasAdjustedTPSData'] = undefined;






export default AllDataModel;

