/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlockInfoProviderStatus from './BlockInfoProviderStatus';

/**
 * The BlockInfoProviderStatusResult model module.
 * @module model/BlockInfoProviderStatusResult
 * @version 1.0
 */
class BlockInfoProviderStatusResult {
    /**
     * Constructs a new <code>BlockInfoProviderStatusResult</code>.
     * @alias module:model/BlockInfoProviderStatusResult
     */
    constructor() { 
        
        BlockInfoProviderStatusResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BlockInfoProviderStatusResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockInfoProviderStatusResult} obj Optional instance to populate.
     * @return {module:model/BlockInfoProviderStatusResult} The populated <code>BlockInfoProviderStatusResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockInfoProviderStatusResult();

            if (data.hasOwnProperty('status')) {
                obj['status'] = BlockInfoProviderStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BlockInfoProviderStatus} status
 */
BlockInfoProviderStatusResult.prototype['status'] = undefined;

/**
 * @member {String} details
 */
BlockInfoProviderStatusResult.prototype['details'] = undefined;






export default BlockInfoProviderStatusResult;

