/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DataPoint from './DataPoint';

/**
 * The DataResponseModel model module.
 * @module model/DataResponseModel
 * @version 1.0
 */
class DataResponseModel {
    /**
     * Constructs a new <code>DataResponseModel</code>.
     * @alias module:model/DataResponseModel
     */
    constructor() { 
        
        DataResponseModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DataResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DataResponseModel} obj Optional instance to populate.
     * @return {module:model/DataResponseModel} The populated <code>DataResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DataResponseModel();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [DataPoint]);
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/DataPoint>} data
 */
DataResponseModel.prototype['data'] = undefined;

/**
 * @member {String} provider
 */
DataResponseModel.prototype['provider'] = undefined;






export default DataResponseModel;

