/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DataPoint model module.
 * @module model/DataPoint
 * @version 1.0
 */
class DataPoint {
    /**
     * Constructs a new <code>DataPoint</code>.
     * @alias module:model/DataPoint
     */
    constructor() { 
        
        DataPoint.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DataPoint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DataPoint} obj Optional instance to populate.
     * @return {module:model/DataPoint} The populated <code>DataPoint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DataPoint();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('blockNumber')) {
                obj['blockNumber'] = ApiClient.convertToType(data['blockNumber'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} date
 */
DataPoint.prototype['date'] = undefined;

/**
 * @member {Number} value
 */
DataPoint.prototype['value'] = undefined;

/**
 * @member {Number} blockNumber
 */
DataPoint.prototype['blockNumber'] = undefined;






export default DataPoint;

