/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GPSDataPoint model module.
 * @module model/GPSDataPoint
 * @version 1.0
 */
class GPSDataPoint {
    /**
     * Constructs a new <code>GPSDataPoint</code>.
     * @alias module:model/GPSDataPoint
     */
    constructor() { 
        
        GPSDataPoint.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GPSDataPoint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GPSDataPoint} obj Optional instance to populate.
     * @return {module:model/GPSDataPoint} The populated <code>GPSDataPoint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GPSDataPoint();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('gps')) {
                obj['gps'] = ApiClient.convertToType(data['gps'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} date
 */
GPSDataPoint.prototype['date'] = undefined;

/**
 * @member {Number} gps
 */
GPSDataPoint.prototype['gps'] = undefined;






export default GPSDataPoint;

