/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChartData from './ChartData';
import ProviderResponseModel from './ProviderResponseModel';

/**
 * The HomePageResponseModel model module.
 * @module model/HomePageResponseModel
 * @version 1.0
 */
class HomePageResponseModel {
    /**
     * Constructs a new <code>HomePageResponseModel</code>.
     * @alias module:model/HomePageResponseModel
     */
    constructor() { 
        
        HomePageResponseModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HomePageResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HomePageResponseModel} obj Optional instance to populate.
     * @return {module:model/HomePageResponseModel} The populated <code>HomePageResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HomePageResponseModel();

            if (data.hasOwnProperty('chartData')) {
                obj['chartData'] = ChartData.constructFromObject(data['chartData']);
            }
            if (data.hasOwnProperty('maxData')) {
                obj['maxData'] = ApiClient.convertToType(data['maxData'], {'String': Object});
            }
            if (data.hasOwnProperty('instantData')) {
                obj['instantData'] = ApiClient.convertToType(data['instantData'], {'String': Object});
            }
            if (data.hasOwnProperty('colorDictionary')) {
                obj['colorDictionary'] = ApiClient.convertToType(data['colorDictionary'], {'String': 'String'});
            }
            if (data.hasOwnProperty('providerTypesColorDictionary')) {
                obj['providerTypesColorDictionary'] = ApiClient.convertToType(data['providerTypesColorDictionary'], {'String': 'String'});
            }
            if (data.hasOwnProperty('providers')) {
                obj['providers'] = ApiClient.convertToType(data['providers'], [ProviderResponseModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ChartData} chartData
 */
HomePageResponseModel.prototype['chartData'] = undefined;

/**
 * @member {Object.<String, Object>} maxData
 */
HomePageResponseModel.prototype['maxData'] = undefined;

/**
 * @member {Object.<String, Object>} instantData
 */
HomePageResponseModel.prototype['instantData'] = undefined;

/**
 * @member {Object.<String, String>} colorDictionary
 */
HomePageResponseModel.prototype['colorDictionary'] = undefined;

/**
 * @member {Object.<String, String>} providerTypesColorDictionary
 */
HomePageResponseModel.prototype['providerTypesColorDictionary'] = undefined;

/**
 * @member {Array.<module:model/ProviderResponseModel>} providers
 */
HomePageResponseModel.prototype['providers'] = undefined;






export default HomePageResponseModel;

