/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OCLH model module.
 * @module model/OCLH
 * @version 1.0
 */
class OCLH {
    /**
     * Constructs a new <code>OCLH</code>.
     * @alias module:model/OCLH
     */
    constructor() { 
        
        OCLH.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OCLH</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OCLH} obj Optional instance to populate.
     * @return {module:model/OCLH} The populated <code>OCLH</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OCLH();

            if (data.hasOwnProperty('open')) {
                obj['open'] = ApiClient.convertToType(data['open'], 'Number');
            }
            if (data.hasOwnProperty('close')) {
                obj['close'] = ApiClient.convertToType(data['close'], 'Number');
            }
            if (data.hasOwnProperty('low')) {
                obj['low'] = ApiClient.convertToType(data['low'], 'Number');
            }
            if (data.hasOwnProperty('high')) {
                obj['high'] = ApiClient.convertToType(data['high'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} open
 */
OCLH.prototype['open'] = undefined;

/**
 * @member {Number} close
 */
OCLH.prototype['close'] = undefined;

/**
 * @member {Number} low
 */
OCLH.prototype['low'] = undefined;

/**
 * @member {Number} high
 */
OCLH.prototype['high'] = undefined;






export default OCLH;

