/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProviderResponseModel model module.
 * @module model/ProviderResponseModel
 * @version 1.0
 */
class ProviderResponseModel {
    /**
     * Constructs a new <code>ProviderResponseModel</code>.
     * @alias module:model/ProviderResponseModel
     */
    constructor() { 
        
        ProviderResponseModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProviderResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProviderResponseModel} obj Optional instance to populate.
     * @return {module:model/ProviderResponseModel} The populated <code>ProviderResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProviderResponseModel();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('theoreticalMaxTPS')) {
                obj['theoreticalMaxTPS'] = ApiClient.convertToType(data['theoreticalMaxTPS'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('isGeneralPurpose')) {
                obj['isGeneralPurpose'] = ApiClient.convertToType(data['isGeneralPurpose'], 'Boolean');
            }
            if (data.hasOwnProperty('isSubchainOf')) {
                obj['isSubchainOf'] = ApiClient.convertToType(data['isSubchainOf'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
ProviderResponseModel.prototype['name'] = undefined;

/**
 * @member {String} color
 */
ProviderResponseModel.prototype['color'] = undefined;

/**
 * @member {Number} theoreticalMaxTPS
 */
ProviderResponseModel.prototype['theoreticalMaxTPS'] = undefined;

/**
 * @member {String} type
 */
ProviderResponseModel.prototype['type'] = undefined;

/**
 * @member {Boolean} isGeneralPurpose
 */
ProviderResponseModel.prototype['isGeneralPurpose'] = undefined;

/**
 * @member {String} isSubchainOf
 */
ProviderResponseModel.prototype['isSubchainOf'] = undefined;






export default ProviderResponseModel;

