/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProviderType from './ProviderType';

/**
 * The Provider model module.
 * @module model/Provider
 * @version 1.0
 */
class Provider {
    /**
     * Constructs a new <code>Provider</code>.
     * @alias module:model/Provider
     */
    constructor() { 
        
        Provider.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Provider</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Provider} obj Optional instance to populate.
     * @return {module:model/Provider} The populated <code>Provider</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Provider();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
            if (data.hasOwnProperty('typeNavigation')) {
                obj['typeNavigation'] = ProviderType.constructFromObject(data['typeNavigation']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Provider.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Provider.prototype['name'] = undefined;

/**
 * @member {Number} type
 */
Provider.prototype['type'] = undefined;

/**
 * @member {module:model/ProviderType} typeNavigation
 */
Provider.prototype['typeNavigation'] = undefined;






export default Provider;

