/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProviderInfo model module.
 * @module model/ProviderInfo
 * @version 1.0
 */
class ProviderInfo {
    /**
     * Constructs a new <code>ProviderInfo</code>.
     * @alias module:model/ProviderInfo
     */
    constructor() { 
        
        ProviderInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProviderInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProviderInfo} obj Optional instance to populate.
     * @return {module:model/ProviderInfo} The populated <code>ProviderInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProviderInfo();

            if (data.hasOwnProperty('maxTPS')) {
                obj['maxTPS'] = ApiClient.convertToType(data['maxTPS'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} maxTPS
 */
ProviderInfo.prototype['maxTPS'] = undefined;

/**
 * @member {String} name
 */
ProviderInfo.prototype['name'] = undefined;

/**
 * @member {String} type
 */
ProviderInfo.prototype['type'] = undefined;






export default ProviderInfo;

