/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OCLH from './OCLH';

/**
 * The TPSGPSOCLH model module.
 * @module model/TPSGPSOCLH
 * @version 1.0
 */
class TPSGPSOCLH {
    /**
     * Constructs a new <code>TPSGPSOCLH</code>.
     * @alias module:model/TPSGPSOCLH
     */
    constructor() { 
        
        TPSGPSOCLH.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TPSGPSOCLH</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TPSGPSOCLH} obj Optional instance to populate.
     * @return {module:model/TPSGPSOCLH} The populated <code>TPSGPSOCLH</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TPSGPSOCLH();

            if (data.hasOwnProperty('tps')) {
                obj['tps'] = OCLH.constructFromObject(data['tps']);
            }
            if (data.hasOwnProperty('gps')) {
                obj['gps'] = OCLH.constructFromObject(data['gps']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/OCLH} tps
 */
TPSGPSOCLH.prototype['tps'] = undefined;

/**
 * @member {module:model/OCLH} gps
 */
TPSGPSOCLH.prototype['gps'] = undefined;






export default TPSGPSOCLH;

