/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TPSDataPoint from './TPSDataPoint';

/**
 * The TPSResponseModel model module.
 * @module model/TPSResponseModel
 * @version 1.0
 */
class TPSResponseModel {
    /**
     * Constructs a new <code>TPSResponseModel</code>.
     * @alias module:model/TPSResponseModel
     */
    constructor() { 
        
        TPSResponseModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TPSResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TPSResponseModel} obj Optional instance to populate.
     * @return {module:model/TPSResponseModel} The populated <code>TPSResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TPSResponseModel();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [TPSDataPoint]);
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TPSDataPoint>} data
 */
TPSResponseModel.prototype['data'] = undefined;

/**
 * @member {String} provider
 */
TPSResponseModel.prototype['provider'] = undefined;






export default TPSResponseModel;

