/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DataPoint from '../model/DataPoint';
import DataResponseModel from "../model/DataResponseModel";
/**
* GPS service.
* @module api/GPSApi
* @version 1.0
*/
export default class GPSApi {

    /**
    * Constructs a new GPSApi. 
    * @alias module:api/GPSApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the aPIGPSGeMonthlyDataByYearGet operation.
     * @callback module:api/GPSApi~aPIGPSGeMonthlyDataByYearGetCallback
     * @param {String} error Error message, if any.
     * @param {Object.<String, {String: [DataResponseModel]}>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.provider 
     * @param {String} opts.network 
     * @param {Boolean} opts.includeSidechains 
     * @param {Number} opts.year 
     * @param {module:api/GPSApi~aPIGPSGeMonthlyDataByYearGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object.<String, {String: [DataResponseModel]}>}
     */
    aPIGPSGeMonthlyDataByYearGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'Provider': opts['provider'],
        'Network': opts['network'],
        'IncludeSidechains': opts['includeSidechains'],
        'year': opts['year']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = {'String': [DataResponseModel]};
      return this.apiClient.callApi(
        '/API/GPS/GeMonthlyDataByYear', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the aPIGPSGetGet operation.
     * @callback module:api/GPSApi~aPIGPSGetGetCallback
     * @param {String} error Error message, if any.
     * @param {Object.<String, {String: [DataResponseModel]}>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.provider 
     * @param {String} opts.network 
     * @param {Boolean} opts.includeSidechains 
     * @param {String} opts.interval 
     * @param {module:api/GPSApi~aPIGPSGetGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object.<String, {String: [DataResponseModel]}>}
     */
    aPIGPSGetGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'Provider': opts['provider'],
        'Network': opts['network'],
        'IncludeSidechains': opts['includeSidechains'],
        'interval': opts['interval']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = {'String': [DataResponseModel]};
      return this.apiClient.callApi(
        '/API/GPS/Get', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the aPIGPSInstantGet operation.
     * @callback module:api/GPSApi~aPIGPSInstantGetCallback
     * @param {String} error Error message, if any.
     * @param {Object.<String, {String: [DataPoint]}>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.provider 
     * @param {String} opts.network 
     * @param {Boolean} opts.includeSidechains 
     * @param {module:api/GPSApi~aPIGPSInstantGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object.<String, {String: [DataPoint]}>}
     */
    aPIGPSInstantGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'Provider': opts['provider'],
        'Network': opts['network'],
        'IncludeSidechains': opts['includeSidechains']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = {'String': [DataPoint]};
      return this.apiClient.callApi(
        '/API/GPS/Instant', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the aPIGPSMaxGet operation.
     * @callback module:api/GPSApi~aPIGPSMaxGetCallback
     * @param {String} error Error message, if any.
     * @param {Object.<String, module:model/{String: DataPoint}>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.provider 
     * @param {String} opts.network 
     * @param {Boolean} opts.includeSidechains 
     * @param {module:api/GPSApi~aPIGPSMaxGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object.<String, module:model/{String: DataPoint}>}
     */
    aPIGPSMaxGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'Provider': opts['provider'],
        'Network': opts['network'],
        'IncludeSidechains': opts['includeSidechains']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = {'String': DataPoint};
      return this.apiClient.callApi(
        '/API/GPS/Max', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
