/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import TPSGPSOCLH from '../model/TPSGPSOCLH';

/**
* OCLH service.
* @module api/OCLHApi
* @version 1.0
*/
export default class OCLHApi {

    /**
    * Constructs a new OCLHApi. 
    * @alias module:api/OCLHApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the aPIOCLHOCLHGet operation.
     * @callback module:api/OCLHApi~aPIOCLHOCLHGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TPSGPSOCLH>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.interval 
     * @param {String} opts.provider 
     * @param {String} opts.network 
     * @param {module:api/OCLHApi~aPIOCLHOCLHGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TPSGPSOCLH>}
     */
    aPIOCLHOCLHGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'interval': opts['interval'],
        'provider': opts['provider'],
        'network': opts['network']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [TPSGPSOCLH];
      return this.apiClient.callApi(
        '/API/OCLH/OCLH', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
