/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataResponseModel } from './DataResponseModel';
import { ProviderModel } from './ProviderModel';
import { HttpFile } from '../http/http';

export class AllDataModel {
    'providers'?: Array<ProviderModel>;
    'maxData'?: { [key: string]: any; };
    'allTPSData'?: { [key: string]: { [key: string]: Array<DataResponseModel>; }; };
    'allGPSData'?: { [key: string]: { [key: string]: Array<DataResponseModel>; }; };
    'allGasAdjustedTPSData'?: { [key: string]: { [key: string]: Array<DataResponseModel>; }; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "providers",
            "baseName": "providers",
            "type": "Array<ProviderModel>",
            "format": ""
        },
        {
            "name": "maxData",
            "baseName": "maxData",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "allTPSData",
            "baseName": "allTPSData",
            "type": "{ [key: string]: { [key: string]: Array<DataResponseModel>; }; }",
            "format": ""
        },
        {
            "name": "allGPSData",
            "baseName": "allGPSData",
            "type": "{ [key: string]: { [key: string]: Array<DataResponseModel>; }; }",
            "format": ""
        },
        {
            "name": "allGasAdjustedTPSData",
            "baseName": "allGasAdjustedTPSData",
            "type": "{ [key: string]: { [key: string]: Array<DataResponseModel>; }; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AllDataModel.attributeTypeMap;
    }

    public constructor() {
    }
}

