/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataResponseModel } from './DataResponseModel';
import { DataType } from './DataType';
import { HttpFile } from '../http/http';

export class ChartData {
    'data'?: { [key: string]: Array<DataResponseModel>; };
    'dataType'?: DataType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "{ [key: string]: Array<DataResponseModel>; }",
            "format": ""
        },
        {
            "name": "dataType",
            "baseName": "dataType",
            "type": "DataType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChartData.attributeTypeMap;
    }

    public constructor() {
    }
}

