/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProviderResponseModel {
    'name'?: string;
    'color'?: string;
    'theoreticalMaxTPS'?: number;
    'type'?: string;
    'isGeneralPurpose'?: boolean;
    'isSubchainOf'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "theoreticalMaxTPS",
            "baseName": "theoreticalMaxTPS",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "isGeneralPurpose",
            "baseName": "isGeneralPurpose",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isSubchainOf",
            "baseName": "isSubchainOf",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProviderResponseModel.attributeTypeMap;
    }

    public constructor() {
    }
}

