version: '3.4'
  ethtps.api:
    restart: always
    image: ${DOCKER_REGISTRY-}ethtpsapi
    expose:
      - "6430"
    ports:
      - "6430:6430"
    build:
      context: .
      dockerfile: ETHTPS.API/Dockerfile
