Table dbo.Providers{
  ID int [pk, increment]
  Name varchar [unique, not null]
  Type int [not null]
  Color varchar(16) [not null]
  IsGeneralPurpose bit
  HistoricalAggregationDeltaBlock int
  Enabled bit [not null]
  SubchainOf int
}

Ref: dbo.Providers.Type > dbo.ProviderTypes.ID
Ref: dbo.Providers.SubchainOf > dbo.Providers.ID

Table dbo.ProviderTypes{
  ID int [pk, increment]
  Name varchar [unique, not null]
  Color varchar(16) [not null]
  Enabled bit [not null]
}

Table dbo.AccesStats{
  ID int [pk, increment]
  Project varchar [not null]
  Path varchar [not null]
  Count int [not null]
  AverageRequestTimeMs float [not null]
}

Table dbo.DetailedAccessStats{
  ID int [pk, increment]
  Path varchar [not null]
  RequestTimeMs float [not null]
  IPAddress varchar [not null]
  Date datetime [not null]
}

Table dbo.CachedResponses{
  ID int [pk, increment]
  Name varchar [unique, not null]
  JSON varchar(max) 
}

Table dbo.Networks{
  ID int [pk, increment]
  Name varchar [unique, not null]
}

Table dbo.TPSAndGasData_Latest {
  ID int [pk, increment]
  Provider int [unique, not null]
  Network int [not null]
  TPS float [not null]
  GPS float [not null]
  LastUpdate datetime
}

Ref: dbo.TPSAndGasData_Latest.Provider > dbo.Providers.ID
Ref: dbo.TPSAndGasData_Latest.Network > dbo.Networks.ID


Table dbo.TPSAndGasData_Max {
  ID int [pk, increment]
  Provider int [unique, not null]
  Network int [not null]
  Date datetime [not null]
  MaxTPS float [not null]
  MaxGPS float [not null]
  MaxTPSBlockNumber int
  MaxGPSBlockNumber int
}

Ref: dbo.TPSAndGasData_Max.Provider > dbo.Providers.ID
Ref: dbo.TPSAndGasData_Max.Network > dbo.Networks.ID


Table dbo.TPSAndGasData_Hour{
  ID int [pk, increment]
  Network int [not null]
  Provider int [not null]
  StartDate datetime [not null]
  AverageTPS float [not null]
  AverageGPS float [not null]
  ReadingsCount int [not null]
  OCLH_JSON varchar
}

Ref: dbo.TPSAndGasData_Hour.Provider > dbo.Providers.ID
Ref: dbo.TPSAndGasData_Hour.Network > dbo.Networks.ID


Table dbo.TPSAndGasData_Day{
  ID int [pk, increment]
  Network int [not null]
  Provider int [not null]
  StartDate datetime [not null]
  AverageTPS float [not null]
  AverageGPS float [not null]
  ReadingsCount int [not null]
  OCLH_JSON varchar
}

Ref: dbo.TPSAndGasData_Day.Provider > dbo.Providers.ID
Ref: dbo.TPSAndGasData_Day.Network > dbo.Networks.ID


Table dbo.TPSAndGasData_Week{
  ID int [pk, increment]
  Network int [not null]
  Provider int [not null]
  StartDate datetime [not null]
  AverageTPS float [not null]
  AverageGPS float [not null]
  ReadingsCount int [not null]
  OCLH_JSON varchar
}

Ref: dbo.TPSAndGasData_Week.Provider > dbo.Providers.ID
Ref: dbo.TPSAndGasData_Week.Network > dbo.Networks.ID

Table dbo.TPSAndGasData_Minute {
  ID int [pk, increment]
  Network int [not null]
  Provider int [not null]
  StartDate datetime [not null]
  AverageTPS float [not null]
  AverageGPS float [not null]
  ReadingsCount int [not null]
}

Ref: dbo.TPSAndGasData_Minute.Provider > dbo.Providers.ID
Ref: dbo.TPSAndGasData_Minute.Network > dbo.Networks.ID

Table dbo.TPSAndGasData_Month{
  ID int [pk, increment]
  Network int [not null]
  Provider int [not null]
  StartDate datetime [not null]
  AverageTPS float [not null]
  AverageGPS float [not null]
  ReadingsCount int [not null]
}

Ref: dbo.TPSAndGasData_Month.Provider > dbo.Providers.ID
Ref: dbo.TPSAndGasData_Month.Network > dbo.Networks.ID

Table dbo.TPSAndGasData_Year{
  ID int [pk, increment]
  Network int [not null]
  Provider int [not null]
  StartDate datetime [not null]
  AverageTPS float [not null]
  AverageGPS float [not null]
  ReadingsCount int [not null]
}

Ref: dbo.TPSAndGasData_Year.Provider > dbo.Providers.ID
Ref: dbo.TPSAndGasData_Year.Network > dbo.Networks.ID

Table dbo.TPSAndGasData_All {
  ID int [pk, increment]
  Network int [not null]
  Provider int [not null]
  StartDate datetime [not null]
  AverageTPS float [not null]
  AverageGPS float [not null]
  ReadingsCount int [not null]
}

Ref: dbo.TPSAndGasData_All.Provider > dbo.Providers.ID
Ref: dbo.TPSAndGasData_All.Network > dbo.Networks.ID

Table dbo.OldestLoggedHistoricalEntries{
  ID int [pk, increment]
  Network int [not null]
  Provider int [not null]
  OldestBlock int [not null]
}

Ref: dbo.OldestLoggedHistoricalEntries.Provider > dbo.Providers.ID
Ref: dbo.OldestLoggedHistoricalEntries.Network > dbo.Networks.ID

Table Security.APIKeys{
  ID int [pk, increment]
  KeyHash varchar [not null]
  TotalCalls int [not null]
  CallsLast24h int [not null]
  Limit24h int [not null]
  RequesterIPAddress varchar [not null]
}

Table Security.APIKeyGroups {
  ID int [pk, increment]
  APIKeyID int [not null]
  GroupID int [not null]
}

Table Security.Roles{
  ID int [pk, increment]
  Name varchar [not null]
  
}

Ref: Security.APIKeyGroups.APIKeyID > Security.APIKeys.ID
Ref: Security.APIKeyGroups.GroupID > Security.Groups.ID


Table Security.Groups {
  ID int [pk, increment]
  Name varchar [not null]
 }
 
Table Security.Permissions {
  ID int [pk, increment]
  Name varchar [not null]
}

Table Security.PermissionsForRoles{
  ID int [pk, increment]
  RoleID int [not null]
  PermissionID int [not null]
}

Ref: Security.PermissionsForRoles.RoleID > Security.Roles.ID
Ref: Security.PermissionsForRoles.PermissionID > Security.Permissions.ID

Table Security.GroupRoles {
  ID int [pk, increment]
  GroupID int [not null]
  RoleID int [not null]
}

Ref: Security.GroupRoles.GroupID > Security.Groups.ID
Ref: Security.GroupRoles.RoleID > Security.Roles.ID

Table dbo.TimeWarpData{
   ID int [pk, increment]
   Network int [not null]
   Provider int [not null]
   Block int
   StartDate datetime [not null]
   AverageTPS float [not null]
   AverageGPS float [not null]
}

Ref: dbo.TimeWarpData.Provider > dbo.Providers.ID
Ref: dbo.TimeWarpData.Network > dbo.Networks.ID

Table dbo.TimeWarpData_Minute{
   ID int [pk, increment]
   Network int [not null]
   Provider int [not null]
   Block int
   StartDate datetime [not null]
   AverageTPS float [not null]
   AverageGPS float [not null]
}

Ref: dbo.TimeWarpData_Minute.Provider > dbo.Providers.ID
Ref: dbo.TimeWarpData_Minute.Network > dbo.Networks.ID

Table dbo.TimeWarpData_Hour{
   ID int [pk, increment]
   Network int [not null]
   Provider int [not null]
   Block int
   StartDate datetime [not null]
   AverageTPS float [not null]
   AverageGPS float [not null]
}

Ref: dbo.TimeWarpData_Hour.Provider > dbo.Providers.ID
Ref: dbo.TimeWarpData_Hour.Network > dbo.Networks.ID

Table dbo.TimeWarpData_Day{
   ID int [pk, increment]
   Network int [not null]
   Provider int [not null]
   Block int
   StartDate datetime [not null]
   AverageTPS float [not null]
   AverageGPS float [not null]
}

Ref: dbo.TimeWarpData_Day.Provider > dbo.Providers.ID
Ref: dbo.TimeWarpData_Day.Network > dbo.Networks.ID

Table dbo.TimeWarpData_Week{
   ID int [pk, increment]
   Network int [not null]
   Provider int [not null]
   Block int
   StartDate datetime [not null]
   AverageTPS float [not null]
   AverageGPS float [not null]
}

Ref: dbo.TimeWarpData_Week.Provider > dbo.Providers.ID
Ref: dbo.TimeWarpData_Week.Network > dbo.Networks.ID

Table dbo.OldestLoggedTimeWarpBlocks {
  ID int [pk, increment]
  Network int [not null]
  Provider int [not null]
  OldestBlock int [not null]
}

Ref: dbo.OldestLoggedTimeWarpBlocks.Provider > dbo.Providers.ID
Ref: dbo.OldestLoggedTimeWarpBlocks.Network > dbo.Networks.ID

Table dbo.StarkwareTransactionCountData {
  ID int [pk, increment]
  Network int [not null]
  Product varchar [not null]
  LastUpdateTime datetime [not null]
  LastUpdateCount int [not null]
  LastUpdateTPS float [not null]
}

Ref: dbo.StarkwareTransactionCountData.Network > dbo.Networks.ID

Table ABTesting.APIKeyExperimentBinding{
  ID int [pk, increment]
  ExperimentID int [not null]
  APIKeyID int [not null]
}

Ref: ABTesting.APIKeyExperimentBinding.ExperimentID > ABTesting.Experiments.ID
Ref: ABTesting.APIKeyExperimentBinding.APIKeyID > Security.APIKeys.ID

Table ABTesting.ExperimentTargetTypes{
  ID int [pk, increment]
  TargetTypeName varchar [not null]
  TargetTypeValue varchar [not null]
}

Table ABTesting.ExperimentTargets{
  ID int [pk, increment]
  Name varchar [not null]
  Description varchar
  Type int [not null]
}

Ref: ABTesting.ExperimentTargets.Type > ABTesting.ExperimentTargetTypes.ID

Table ABTesting.ExperimentRunParameters{
  ID int [pk, increment]
  StartDate datetime
  EndDate datetime
  Enabled bit [not null]
  DisplayToNPeopleBeforeEnd int
  ConsiderFinishedAfterTimeoutSeconds int [not null]
}

Table ABTesting.Experiments {
  ID int [pk, increment]
  ProjectID int [not null]
  Name varchar [not null]
  Description varchar
  Target int [not null]
  RunParameters int [not null]
}

Table ABTesting.ExperimentResults{
   ID int [pk, increment]
   Experiment int [not null]
   AverageRetentionSeconds int [not null]
   SDRetentionSeconds int [not null]
   AveragePercentageReturnVisitors int [not null]
   SDPercentageReturnVisitors int [not null]
}

Table ABTesting.ExperimentalSessions{
  ID int [pk, increment]
  Experiment int [not null]
  TargetIPAddress varchar [not null]
  RetentionSeconds int [not null]
}

Table ABTesting.ExperimentFeedback {
   ID int [pk, increment]
   Experiment int [not null]
   Vote bit
   Rating int
   Text varchar
}
Ref: ABTesting.ExperimentFeedback.Experiment > ABTesting.Experiments.ID

Ref: ABTesting.ExperimentalSessions.ID > ABTesting.Experiments.ID
Ref: ABTesting.ExperimentResults.Experiment > ABTesting.Experiments.ID

Ref: ABTesting.Experiments.RunParameters > ABTesting.ExperimentRunParameters.ID

Ref: ABTesting.Experiments.Target > ABTesting.ExperimentTargets.ID

Ref: ABTesting.Experiments.ProjectID > dbo.Providers.ID

Table ProjectManagement.Projects {
  ID int [pk, increment]
  Enabled bit [not null]
  Provider int
  Name varchar [not null]
  Website varchar [not null]
  Details varchar
}

Ref: ProjectManagement.Projects.Provider > dbo.Providers.ID

Table Info.ExternalWebsites {
  ID int [pk, increment]
  Name varchar [not null]
  IconBase64 varchar(max) [not null] 
  Category int [not null]
}


Table Info.ExternalWebsiteCateopry {
  ID int [pk, increment]
  Name varchar [not null]
}

Ref: Info.ExternalWebsites.Category > Info.ExternalWebsiteCateopry.ID
Table Info.ProviderLinks {
    ID int [pk, increment]
    ProviderID int [not null]
    ExternalWebsiteID int [not null]
    Link varchar [not null]
}

Ref: Info.ProviderLinks.ProviderID > dbo.Providers.ID
Ref: Info.ProviderLinks.ExternalWebsiteID > Info.ExternalWebsites.ID

Table Info.MarkdownPages{
  ID int [pk, increment]
  RawMarkdown varchar(max) [not null]
}

Table Info.ProviderDetailsMarkdownPages {
  ID int [pk, increment]
  ProviderID int [not null]
  MarkdownPageID int [not null]
}

Ref: Info.ProviderDetailsMarkdownPages.ProviderID > dbo.Providers.ID
Ref: Info.ProviderDetailsMarkdownPages.MarkdownPageID > Info.MarkdownPages.ID

Table Configuration.ConfigurationStrings {
  ID int [pk, increment]
  Name varchar [not null]
  Value varchar [not null]
}

Table Configuration.Environments {
  ID int [pk, increment]
  Name varchar [not null]
}

Table Microservices.Microservices {
  ID int [pk, increment]
  Name varchar [not null]
  Description varchar
}

Table Configuration.MicroserviceConfigurationStrings {
  ID int [pk, increment]
  MicroserviceID int [not null]
  ConfigurationStringID int [not null]
  EnvironmentID int [not null]
}

Ref: Configuration.MicroserviceConfigurationStrings.MicroserviceID > Microservices.Microservices.ID
Ref: Configuration.MicroserviceConfigurationStrings.ConfigurationStringID > Configuration.ConfigurationStrings.ID
Ref: Configuration.MicroserviceConfigurationStrings.EnvironmentID > Configuration.Environments.ID

Table Configuration.ProviderConfigurationStrings {
  ID int [pk, increment]
  ProviderID int [not null]
  ConfigurationStringID int [not null]
  EnvironmentID int [not null]
}

Ref: Configuration.ProviderConfigurationStrings.ProviderID > dbo.Providers.ID
Ref: Configuration.ProviderConfigurationStrings.ConfigurationStringID > Configuration.ConfigurationStrings.ID

Table Logging.Logs{
  ID int [pk, increment]
  Values varchar(max) [not null]
  Created datetime [not null]
  EnvironmentID int [not null]
  CreatedBy int [not null]
}

Ref: Logging.Logs.EnvironmentID > Configuration.Environments.ID
Ref: Logging.Logs.CreatedBy > Microservices.Microservices.ID
Ref: Configuration.ProviderConfigurationStrings.EnvironmentID > Configuration.Environments.ID

Table DataUpdaters.DataUpdaterTypes{
  ID int [pk, increment]
  TypeName varchar [not null]
}

Table DataUpdaters.DataUpdaters{
  ID int [pk, increment]
  TypeID int [not null]
  ProviderID int [not null]
}

Ref: DataUpdaters.DataUpdaters.TypeID > DataUpdaters.DataUpdaterTypes.ID
Ref: DataUpdaters.DataUpdaters.ProviderID > dbo.Providers.ID

Table DataUpdaters.DataUpdaterStatuses{
  ID int [pk, increment]
  Name varchar [not null]
}

Table DataUpdaters.LiveDataUpdaterStatuses{
  ID int [pk, increment]
  UpdaterID int [not null]
  StatusID int [not null]
  LastSuccessfulRunTime datetime
  NumberOfSuccesses int [not null, default: 0]
  NumberOfFailures int [not null, default: 0]
}

Ref: DataUpdaters.LiveDataUpdaterStatuses.UpdaterID > DataUpdaters.DataUpdaters.ID
Ref: DataUpdaters.LiveDataUpdaterStatuses.StatusID > DataUpdaters.DataUpdaterStatuses.ID