Table Providers{
  ID int [pk, increment]
  Name varchar
  Type int
}

Ref: Providers.Type > ProviderTypes.ID

Table ProviderTypes{
  ID int [pk, increment]
  Name varchar
}

Table ProviderProperties{
  ID int [pk, increment]
  Provider int
  Name varchar
  Value varchar
}

Ref: ProviderProperties.Provider > Providers.ID

Table TPSData{
  ID int [pk, increment]
  Network int
  Provider int
  Date datetime
  Block varchar
  TPS float
}

Ref: TPSData.Provider > Providers.ID
Ref: TPSData.Network > Networks.ID

Table AccesStats{
  ID int [pk, increment]
  Project varchar
  Path varchar
  Count int
  AverageRequestTimeMs float
  ExternalCount int
}

Table CachedResponses{
  ID int [pk, increment]
  Name varchar
  JSON varchar(max)
}

Table Networks{
  ID int [pk, increment]
  Name varchar
}

Table LatestEntries{
  ID int [pk, increment]
  Provider int
  Entry int
}

Ref: LatestEntries.Provider > Providers.ID
Ref: LatestEntries.Entry > TPSData.ID

Table MaxTPSEntries{
  ID int [pk, increment]
  Provider int
  Entry int
}

Ref: MaxTPSEntries.Provider > Providers.ID
Ref: MaxTPSEntries.Entry > TPSData.ID

Table TaskPerformanceMetrics{
  ID int [pk, increment]
  Machine int
  TaskName varchar
  RunCount int
  AverageRunTime float
}

Ref: TaskPerformanceMetrics.Machine > MachineConfigurations.ID

Table MachineConfigurations{
  ID int [pk, increment]
  Name varchar
  CPUCoreCount int
  TotalRAM int
}

Table TPSData_Hour{
  ID int [pk, increment]
  Network int
  Provider int
  StartDate datetime
  AverageTPS float
  ReadingsCount int
}

Ref: TPSData_Hour.Provider > Providers.ID
Ref: TPSData_Hour.Network > Networks.ID


Table TPSData_Day{
  ID int [pk, increment]
  Network int
  Provider int
  StartDate datetime
  AverageTPS float
  ReadingsCount int
}

Ref: TPSData_Day.Provider > Providers.ID
Ref: TPSData_Day.Network > Networks.ID


Table TPSData_Week{
  ID int [pk, increment]
  Network int
  Provider int
  StartDate datetime
  AverageTPS float
  ReadingsCount int
}

Ref: TPSData_Week.Provider > Providers.ID
Ref: TPSData_Week.Network > Networks.ID

Table TPSData_Month{
  ID int [pk, increment]
  Network int
  Provider int
  StartDate datetime
  AverageTPS float
  ReadingsCount int
}

Ref: TPSData_Month.Provider > Providers.ID
Ref: TPSData_Month.Network > Networks.ID
