/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIKeyResponseModel
 */
export interface APIKeyResponseModel {
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponseModel
     */
    key?: string | null;
    /**
     * 
     * @type {number}
     * @memberof APIKeyResponseModel
     */
    requestLimit24h?: number;
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponseModel
     */
    requesterIP?: string | null;
}

/**
 * Check if a given object implements the APIKeyResponseModel interface.
 */
export function instanceOfAPIKeyResponseModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function APIKeyResponseModelFromJSON(json: any): APIKeyResponseModel {
    return APIKeyResponseModelFromJSONTyped(json, false);
}

export function APIKeyResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIKeyResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'requestLimit24h': !exists(json, 'requestLimit24h') ? undefined : json['requestLimit24h'],
        'requesterIP': !exists(json, 'requesterIP') ? undefined : json['requesterIP'],
    };
}

export function APIKeyResponseModelToJSON(value?: APIKeyResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'requestLimit24h': value.requestLimit24h,
        'requesterIP': value.requesterIP,
    };
}

