/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BlockInfoProviderStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type BlockInfoProviderStatus = typeof BlockInfoProviderStatus[keyof typeof BlockInfoProviderStatus];


export function BlockInfoProviderStatusFromJSON(json: any): BlockInfoProviderStatus {
    return BlockInfoProviderStatusFromJSONTyped(json, false);
}

export function BlockInfoProviderStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockInfoProviderStatus {
    return json as BlockInfoProviderStatus;
}

export function BlockInfoProviderStatusToJSON(value?: BlockInfoProviderStatus | null): any {
    return value as any;
}

