/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlockInfoProviderStatus } from './BlockInfoProviderStatus';
import {
    BlockInfoProviderStatusFromJSON,
    BlockInfoProviderStatusFromJSONTyped,
    BlockInfoProviderStatusToJSON,
} from './BlockInfoProviderStatus';

/**
 * 
 * @export
 * @interface BlockInfoProviderStatusResult
 */
export interface BlockInfoProviderStatusResult {
    /**
     * 
     * @type {BlockInfoProviderStatus}
     * @memberof BlockInfoProviderStatusResult
     */
    status?: BlockInfoProviderStatus;
    /**
     * 
     * @type {string}
     * @memberof BlockInfoProviderStatusResult
     */
    details?: string | null;
}

/**
 * Check if a given object implements the BlockInfoProviderStatusResult interface.
 */
export function instanceOfBlockInfoProviderStatusResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BlockInfoProviderStatusResultFromJSON(json: any): BlockInfoProviderStatusResult {
    return BlockInfoProviderStatusResultFromJSONTyped(json, false);
}

export function BlockInfoProviderStatusResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockInfoProviderStatusResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : BlockInfoProviderStatusFromJSON(json['status']),
        'details': !exists(json, 'details') ? undefined : json['details'],
    };
}

export function BlockInfoProviderStatusResultToJSON(value?: BlockInfoProviderStatusResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': BlockInfoProviderStatusToJSON(value.status),
        'details': value.details,
    };
}

