/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.info API
 * Backend definition for ethtps.info; you\'re free to play around
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Experiment } from './Experiment';
import {
    ExperimentFromJSON,
    ExperimentFromJSONTyped,
    ExperimentToJSON,
} from './Experiment';

/**
 * 
 * @export
 * @interface ExperimentalSession
 */
export interface ExperimentalSession {
    /**
     * 
     * @type {number}
     * @memberof ExperimentalSession
     */
    experiment?: number;
    /**
     * 
     * @type {string}
     * @memberof ExperimentalSession
     */
    targetIpaddress?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExperimentalSession
     */
    retentionSeconds?: number;
    /**
     * 
     * @type {Experiment}
     * @memberof ExperimentalSession
     */
    idNavigation?: Experiment;
    /**
     * 
     * @type {number}
     * @memberof ExperimentalSession
     */
    id?: number;
}

/**
 * Check if a given object implements the ExperimentalSession interface.
 */
export function instanceOfExperimentalSession(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExperimentalSessionFromJSON(json: any): ExperimentalSession {
    return ExperimentalSessionFromJSONTyped(json, false);
}

export function ExperimentalSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentalSession {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'experiment': !exists(json, 'experiment') ? undefined : json['experiment'],
        'targetIpaddress': !exists(json, 'targetIpaddress') ? undefined : json['targetIpaddress'],
        'retentionSeconds': !exists(json, 'retentionSeconds') ? undefined : json['retentionSeconds'],
        'idNavigation': !exists(json, 'idNavigation') ? undefined : ExperimentFromJSON(json['idNavigation']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function ExperimentalSessionToJSON(value?: ExperimentalSession | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'experiment': value.experiment,
        'targetIpaddress': value.targetIpaddress,
        'retentionSeconds': value.retentionSeconds,
        'idNavigation': ExperimentToJSON(value.idNavigation),
        'id': value.id,
    };
}

