/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChartData } from './ChartData';
import {
    ChartDataFromJSON,
    ChartDataFromJSONTyped,
    ChartDataToJSON,
} from './ChartData';
import type { ProviderResponseModel } from './ProviderResponseModel';
import {
    ProviderResponseModelFromJSON,
    ProviderResponseModelFromJSONTyped,
    ProviderResponseModelToJSON,
} from './ProviderResponseModel';

/**
 * 
 * @export
 * @interface HomePageResponseModel
 */
export interface HomePageResponseModel {
    /**
     * 
     * @type {ChartData}
     * @memberof HomePageResponseModel
     */
    chartData?: ChartData;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof HomePageResponseModel
     */
    maxData?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof HomePageResponseModel
     */
    instantData?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HomePageResponseModel
     */
    colorDictionary?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HomePageResponseModel
     */
    providerTypesColorDictionary?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<ProviderResponseModel>}
     * @memberof HomePageResponseModel
     */
    providers?: Array<ProviderResponseModel> | null;
}

/**
 * Check if a given object implements the HomePageResponseModel interface.
 */
export function instanceOfHomePageResponseModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HomePageResponseModelFromJSON(json: any): HomePageResponseModel {
    return HomePageResponseModelFromJSONTyped(json, false);
}

export function HomePageResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): HomePageResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chartData': !exists(json, 'chartData') ? undefined : ChartDataFromJSON(json['chartData']),
        'maxData': !exists(json, 'maxData') ? undefined : json['maxData'],
        'instantData': !exists(json, 'instantData') ? undefined : json['instantData'],
        'colorDictionary': !exists(json, 'colorDictionary') ? undefined : json['colorDictionary'],
        'providerTypesColorDictionary': !exists(json, 'providerTypesColorDictionary') ? undefined : json['providerTypesColorDictionary'],
        'providers': !exists(json, 'providers') ? undefined : (json['providers'] === null ? null : (json['providers'] as Array<any>).map(ProviderResponseModelFromJSON)),
    };
}

export function HomePageResponseModelToJSON(value?: HomePageResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chartData': ChartDataToJSON(value.chartData),
        'maxData': value.maxData,
        'instantData': value.instantData,
        'colorDictionary': value.colorDictionary,
        'providerTypesColorDictionary': value.providerTypesColorDictionary,
        'providers': value.providers === undefined ? undefined : (value.providers === null ? null : (value.providers as Array<any>).map(ProviderResponseModelToJSON)),
    };
}

