/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.info API
 * Backend definition for ethtps.info; you\'re free to play around
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveUpdaterStatus
 */
export interface LiveUpdaterStatus {
    /**
     * 
     * @type {string}
     * @memberof LiveUpdaterStatus
     */
    updater?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveUpdaterStatus
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LiveUpdaterStatus
     */
    updaterType?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof LiveUpdaterStatus
     */
    lastSuccessfulRunTime?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof LiveUpdaterStatus
     */
    numberOfSuccesses?: number;
    /**
     * 
     * @type {number}
     * @memberof LiveUpdaterStatus
     */
    numberOfFailures?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LiveUpdaterStatus
     */
    readonly isUnreliable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LiveUpdaterStatus
     */
    readonly isProbablyDown?: boolean;
}

/**
 * Check if a given object implements the LiveUpdaterStatus interface.
 */
export function instanceOfLiveUpdaterStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LiveUpdaterStatusFromJSON(json: any): LiveUpdaterStatus {
    return LiveUpdaterStatusFromJSONTyped(json, false);
}

export function LiveUpdaterStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveUpdaterStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updater': !exists(json, 'updater') ? undefined : json['updater'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'updaterType': !exists(json, 'updaterType') ? undefined : json['updaterType'],
        'lastSuccessfulRunTime': !exists(json, 'lastSuccessfulRunTime') ? undefined : (json['lastSuccessfulRunTime'] === null ? null : new Date(json['lastSuccessfulRunTime'])),
        'numberOfSuccesses': !exists(json, 'numberOfSuccesses') ? undefined : json['numberOfSuccesses'],
        'numberOfFailures': !exists(json, 'numberOfFailures') ? undefined : json['numberOfFailures'],
        'isUnreliable': !exists(json, 'isUnreliable') ? undefined : json['isUnreliable'],
        'isProbablyDown': !exists(json, 'isProbablyDown') ? undefined : json['isProbablyDown'],
    };
}

export function LiveUpdaterStatusToJSON(value?: LiveUpdaterStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updater': value.updater,
        'status': value.status,
        'updaterType': value.updaterType,
        'lastSuccessfulRunTime': value.lastSuccessfulRunTime === undefined ? undefined : (value.lastSuccessfulRunTime === null ? null : value.lastSuccessfulRunTime.toISOString()),
        'numberOfSuccesses': value.numberOfSuccesses,
        'numberOfFailures': value.numberOfFailures,
    };
}

