/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.info API
 * Backend definition for ethtps.info; you\'re free to play around
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OldestLoggedHistoricalEntry } from './OldestLoggedHistoricalEntry';
import {
    OldestLoggedHistoricalEntryFromJSON,
    OldestLoggedHistoricalEntryFromJSONTyped,
    OldestLoggedHistoricalEntryToJSON,
} from './OldestLoggedHistoricalEntry';
import type { OldestLoggedTimeWarpBlock } from './OldestLoggedTimeWarpBlock';
import {
    OldestLoggedTimeWarpBlockFromJSON,
    OldestLoggedTimeWarpBlockFromJSONTyped,
    OldestLoggedTimeWarpBlockToJSON,
} from './OldestLoggedTimeWarpBlock';
import type { StarkwareTransactionCountDatum } from './StarkwareTransactionCountDatum';
import {
    StarkwareTransactionCountDatumFromJSON,
    StarkwareTransactionCountDatumFromJSONTyped,
    StarkwareTransactionCountDatumToJSON,
} from './StarkwareTransactionCountDatum';
import type { TimeWarpDataDay } from './TimeWarpDataDay';
import {
    TimeWarpDataDayFromJSON,
    TimeWarpDataDayFromJSONTyped,
    TimeWarpDataDayToJSON,
} from './TimeWarpDataDay';
import type { TimeWarpDataHour } from './TimeWarpDataHour';
import {
    TimeWarpDataHourFromJSON,
    TimeWarpDataHourFromJSONTyped,
    TimeWarpDataHourToJSON,
} from './TimeWarpDataHour';
import type { TimeWarpDataMinute } from './TimeWarpDataMinute';
import {
    TimeWarpDataMinuteFromJSON,
    TimeWarpDataMinuteFromJSONTyped,
    TimeWarpDataMinuteToJSON,
} from './TimeWarpDataMinute';
import type { TimeWarpDataWeek } from './TimeWarpDataWeek';
import {
    TimeWarpDataWeekFromJSON,
    TimeWarpDataWeekFromJSONTyped,
    TimeWarpDataWeekToJSON,
} from './TimeWarpDataWeek';
import type { TimeWarpDatum } from './TimeWarpDatum';
import {
    TimeWarpDatumFromJSON,
    TimeWarpDatumFromJSONTyped,
    TimeWarpDatumToJSON,
} from './TimeWarpDatum';
import type { TpsandGasDataAll } from './TpsandGasDataAll';
import {
    TpsandGasDataAllFromJSON,
    TpsandGasDataAllFromJSONTyped,
    TpsandGasDataAllToJSON,
} from './TpsandGasDataAll';
import type { TpsandGasDataDay } from './TpsandGasDataDay';
import {
    TpsandGasDataDayFromJSON,
    TpsandGasDataDayFromJSONTyped,
    TpsandGasDataDayToJSON,
} from './TpsandGasDataDay';
import type { TpsandGasDataHour } from './TpsandGasDataHour';
import {
    TpsandGasDataHourFromJSON,
    TpsandGasDataHourFromJSONTyped,
    TpsandGasDataHourToJSON,
} from './TpsandGasDataHour';
import type { TpsandGasDataLatest } from './TpsandGasDataLatest';
import {
    TpsandGasDataLatestFromJSON,
    TpsandGasDataLatestFromJSONTyped,
    TpsandGasDataLatestToJSON,
} from './TpsandGasDataLatest';
import type { TpsandGasDataMax } from './TpsandGasDataMax';
import {
    TpsandGasDataMaxFromJSON,
    TpsandGasDataMaxFromJSONTyped,
    TpsandGasDataMaxToJSON,
} from './TpsandGasDataMax';
import type { TpsandGasDataMinute } from './TpsandGasDataMinute';
import {
    TpsandGasDataMinuteFromJSON,
    TpsandGasDataMinuteFromJSONTyped,
    TpsandGasDataMinuteToJSON,
} from './TpsandGasDataMinute';
import type { TpsandGasDataMonth } from './TpsandGasDataMonth';
import {
    TpsandGasDataMonthFromJSON,
    TpsandGasDataMonthFromJSONTyped,
    TpsandGasDataMonthToJSON,
} from './TpsandGasDataMonth';
import type { TpsandGasDataWeek } from './TpsandGasDataWeek';
import {
    TpsandGasDataWeekFromJSON,
    TpsandGasDataWeekFromJSONTyped,
    TpsandGasDataWeekToJSON,
} from './TpsandGasDataWeek';
import type { TpsandGasDataYear } from './TpsandGasDataYear';
import {
    TpsandGasDataYearFromJSON,
    TpsandGasDataYearFromJSONTyped,
    TpsandGasDataYearToJSON,
} from './TpsandGasDataYear';

/**
 * 
 * @export
 * @interface Network
 */
export interface Network {
    /**
     * 
     * @type {number}
     * @memberof Network
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Network
     */
    name?: string | null;
    /**
     * 
     * @type {Array<OldestLoggedHistoricalEntry>}
     * @memberof Network
     */
    readonly oldestLoggedHistoricalEntries?: Array<OldestLoggedHistoricalEntry> | null;
    /**
     * 
     * @type {Array<OldestLoggedTimeWarpBlock>}
     * @memberof Network
     */
    readonly oldestLoggedTimeWarpBlocks?: Array<OldestLoggedTimeWarpBlock> | null;
    /**
     * 
     * @type {Array<StarkwareTransactionCountDatum>}
     * @memberof Network
     */
    readonly starkwareTransactionCountData?: Array<StarkwareTransactionCountDatum> | null;
    /**
     * 
     * @type {Array<TimeWarpDatum>}
     * @memberof Network
     */
    readonly timeWarpData?: Array<TimeWarpDatum> | null;
    /**
     * 
     * @type {Array<TimeWarpDataDay>}
     * @memberof Network
     */
    readonly timeWarpDataDays?: Array<TimeWarpDataDay> | null;
    /**
     * 
     * @type {Array<TimeWarpDataHour>}
     * @memberof Network
     */
    readonly timeWarpDataHours?: Array<TimeWarpDataHour> | null;
    /**
     * 
     * @type {Array<TimeWarpDataMinute>}
     * @memberof Network
     */
    readonly timeWarpDataMinutes?: Array<TimeWarpDataMinute> | null;
    /**
     * 
     * @type {Array<TimeWarpDataWeek>}
     * @memberof Network
     */
    readonly timeWarpDataWeeks?: Array<TimeWarpDataWeek> | null;
    /**
     * 
     * @type {Array<TpsandGasDataAll>}
     * @memberof Network
     */
    readonly tpsandGasDataAlls?: Array<TpsandGasDataAll> | null;
    /**
     * 
     * @type {Array<TpsandGasDataDay>}
     * @memberof Network
     */
    readonly tpsandGasDataDays?: Array<TpsandGasDataDay> | null;
    /**
     * 
     * @type {Array<TpsandGasDataHour>}
     * @memberof Network
     */
    readonly tpsandGasDataHours?: Array<TpsandGasDataHour> | null;
    /**
     * 
     * @type {Array<TpsandGasDataLatest>}
     * @memberof Network
     */
    readonly tpsandGasDataLatests?: Array<TpsandGasDataLatest> | null;
    /**
     * 
     * @type {Array<TpsandGasDataMax>}
     * @memberof Network
     */
    readonly tpsandGasDataMaxes?: Array<TpsandGasDataMax> | null;
    /**
     * 
     * @type {Array<TpsandGasDataMinute>}
     * @memberof Network
     */
    readonly tpsandGasDataMinutes?: Array<TpsandGasDataMinute> | null;
    /**
     * 
     * @type {Array<TpsandGasDataMonth>}
     * @memberof Network
     */
    readonly tpsandGasDataMonths?: Array<TpsandGasDataMonth> | null;
    /**
     * 
     * @type {Array<TpsandGasDataWeek>}
     * @memberof Network
     */
    readonly tpsandGasDataWeeks?: Array<TpsandGasDataWeek> | null;
    /**
     * 
     * @type {Array<TpsandGasDataYear>}
     * @memberof Network
     */
    readonly tpsandGasDataYears?: Array<TpsandGasDataYear> | null;
}

/**
 * Check if a given object implements the Network interface.
 */
export function instanceOfNetwork(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NetworkFromJSON(json: any): Network {
    return NetworkFromJSONTyped(json, false);
}

export function NetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Network {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'oldestLoggedHistoricalEntries': !exists(json, 'oldestLoggedHistoricalEntries') ? undefined : (json['oldestLoggedHistoricalEntries'] === null ? null : (json['oldestLoggedHistoricalEntries'] as Array<any>).map(OldestLoggedHistoricalEntryFromJSON)),
        'oldestLoggedTimeWarpBlocks': !exists(json, 'oldestLoggedTimeWarpBlocks') ? undefined : (json['oldestLoggedTimeWarpBlocks'] === null ? null : (json['oldestLoggedTimeWarpBlocks'] as Array<any>).map(OldestLoggedTimeWarpBlockFromJSON)),
        'starkwareTransactionCountData': !exists(json, 'starkwareTransactionCountData') ? undefined : (json['starkwareTransactionCountData'] === null ? null : (json['starkwareTransactionCountData'] as Array<any>).map(StarkwareTransactionCountDatumFromJSON)),
        'timeWarpData': !exists(json, 'timeWarpData') ? undefined : (json['timeWarpData'] === null ? null : (json['timeWarpData'] as Array<any>).map(TimeWarpDatumFromJSON)),
        'timeWarpDataDays': !exists(json, 'timeWarpDataDays') ? undefined : (json['timeWarpDataDays'] === null ? null : (json['timeWarpDataDays'] as Array<any>).map(TimeWarpDataDayFromJSON)),
        'timeWarpDataHours': !exists(json, 'timeWarpDataHours') ? undefined : (json['timeWarpDataHours'] === null ? null : (json['timeWarpDataHours'] as Array<any>).map(TimeWarpDataHourFromJSON)),
        'timeWarpDataMinutes': !exists(json, 'timeWarpDataMinutes') ? undefined : (json['timeWarpDataMinutes'] === null ? null : (json['timeWarpDataMinutes'] as Array<any>).map(TimeWarpDataMinuteFromJSON)),
        'timeWarpDataWeeks': !exists(json, 'timeWarpDataWeeks') ? undefined : (json['timeWarpDataWeeks'] === null ? null : (json['timeWarpDataWeeks'] as Array<any>).map(TimeWarpDataWeekFromJSON)),
        'tpsandGasDataAlls': !exists(json, 'tpsandGasDataAlls') ? undefined : (json['tpsandGasDataAlls'] === null ? null : (json['tpsandGasDataAlls'] as Array<any>).map(TpsandGasDataAllFromJSON)),
        'tpsandGasDataDays': !exists(json, 'tpsandGasDataDays') ? undefined : (json['tpsandGasDataDays'] === null ? null : (json['tpsandGasDataDays'] as Array<any>).map(TpsandGasDataDayFromJSON)),
        'tpsandGasDataHours': !exists(json, 'tpsandGasDataHours') ? undefined : (json['tpsandGasDataHours'] === null ? null : (json['tpsandGasDataHours'] as Array<any>).map(TpsandGasDataHourFromJSON)),
        'tpsandGasDataLatests': !exists(json, 'tpsandGasDataLatests') ? undefined : (json['tpsandGasDataLatests'] === null ? null : (json['tpsandGasDataLatests'] as Array<any>).map(TpsandGasDataLatestFromJSON)),
        'tpsandGasDataMaxes': !exists(json, 'tpsandGasDataMaxes') ? undefined : (json['tpsandGasDataMaxes'] === null ? null : (json['tpsandGasDataMaxes'] as Array<any>).map(TpsandGasDataMaxFromJSON)),
        'tpsandGasDataMinutes': !exists(json, 'tpsandGasDataMinutes') ? undefined : (json['tpsandGasDataMinutes'] === null ? null : (json['tpsandGasDataMinutes'] as Array<any>).map(TpsandGasDataMinuteFromJSON)),
        'tpsandGasDataMonths': !exists(json, 'tpsandGasDataMonths') ? undefined : (json['tpsandGasDataMonths'] === null ? null : (json['tpsandGasDataMonths'] as Array<any>).map(TpsandGasDataMonthFromJSON)),
        'tpsandGasDataWeeks': !exists(json, 'tpsandGasDataWeeks') ? undefined : (json['tpsandGasDataWeeks'] === null ? null : (json['tpsandGasDataWeeks'] as Array<any>).map(TpsandGasDataWeekFromJSON)),
        'tpsandGasDataYears': !exists(json, 'tpsandGasDataYears') ? undefined : (json['tpsandGasDataYears'] === null ? null : (json['tpsandGasDataYears'] as Array<any>).map(TpsandGasDataYearFromJSON)),
    };
}

export function NetworkToJSON(value?: Network | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

