/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.info API
 * Backend definition for ethtps.info; you\'re free to play around
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Network } from './Network';
import {
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
} from './Network';
import type { Provider } from './Provider';
import {
    ProviderFromJSON,
    ProviderFromJSONTyped,
    ProviderToJSON,
} from './Provider';

/**
 * 
 * @export
 * @interface OldestLoggedTimeWarpBlock
 */
export interface OldestLoggedTimeWarpBlock {
    /**
     * 
     * @type {number}
     * @memberof OldestLoggedTimeWarpBlock
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof OldestLoggedTimeWarpBlock
     */
    network?: number;
    /**
     * 
     * @type {number}
     * @memberof OldestLoggedTimeWarpBlock
     */
    provider?: number;
    /**
     * 
     * @type {number}
     * @memberof OldestLoggedTimeWarpBlock
     */
    oldestBlock?: number;
    /**
     * 
     * @type {Network}
     * @memberof OldestLoggedTimeWarpBlock
     */
    networkNavigation?: Network;
    /**
     * 
     * @type {Provider}
     * @memberof OldestLoggedTimeWarpBlock
     */
    providerNavigation?: Provider;
}

/**
 * Check if a given object implements the OldestLoggedTimeWarpBlock interface.
 */
export function instanceOfOldestLoggedTimeWarpBlock(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OldestLoggedTimeWarpBlockFromJSON(json: any): OldestLoggedTimeWarpBlock {
    return OldestLoggedTimeWarpBlockFromJSONTyped(json, false);
}

export function OldestLoggedTimeWarpBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): OldestLoggedTimeWarpBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'network': !exists(json, 'network') ? undefined : json['network'],
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'oldestBlock': !exists(json, 'oldestBlock') ? undefined : json['oldestBlock'],
        'networkNavigation': !exists(json, 'networkNavigation') ? undefined : NetworkFromJSON(json['networkNavigation']),
        'providerNavigation': !exists(json, 'providerNavigation') ? undefined : ProviderFromJSON(json['providerNavigation']),
    };
}

export function OldestLoggedTimeWarpBlockToJSON(value?: OldestLoggedTimeWarpBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'network': value.network,
        'provider': value.provider,
        'oldestBlock': value.oldestBlock,
        'networkNavigation': NetworkToJSON(value.networkNavigation),
        'providerNavigation': ProviderToJSON(value.providerNavigation),
    };
}

