/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.info API
 * Backend definition for ethtps.info; you\'re free to play around
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PermissionsForRole } from './PermissionsForRole';
import {
    PermissionsForRoleFromJSON,
    PermissionsForRoleFromJSONTyped,
    PermissionsForRoleToJSON,
} from './PermissionsForRole';

/**
 * 
 * @export
 * @interface Permission
 */
export interface Permission {
    /**
     * 
     * @type {number}
     * @memberof Permission
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    name?: string | null;
    /**
     * 
     * @type {Array<PermissionsForRole>}
     * @memberof Permission
     */
    readonly permissionsForRoles?: Array<PermissionsForRole> | null;
}

/**
 * Check if a given object implements the Permission interface.
 */
export function instanceOfPermission(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PermissionFromJSON(json: any): Permission {
    return PermissionFromJSONTyped(json, false);
}

export function PermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Permission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'permissionsForRoles': !exists(json, 'permissionsForRoles') ? undefined : (json['permissionsForRoles'] === null ? null : (json['permissionsForRoles'] as Array<any>).map(PermissionsForRoleFromJSON)),
    };
}

export function PermissionToJSON(value?: Permission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

