/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.info API
 * Backend definition for ethtps.info; you\'re free to play around
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IProviderXYMultiConvertible } from './IProviderXYMultiConvertible';
import {
    IProviderXYMultiConvertibleFromJSON,
    IProviderXYMultiConvertibleFromJSONTyped,
    IProviderXYMultiConvertibleToJSON,
} from './IProviderXYMultiConvertible';

/**
 * 
 * @export
 * @interface SimpleMultiDatasetAnalysis
 */
export interface SimpleMultiDatasetAnalysis {
    /**
     * 
     * @type {IProviderXYMultiConvertible}
     * @memberof SimpleMultiDatasetAnalysis
     */
    max?: IProviderXYMultiConvertible;
    /**
     * 
     * @type {IProviderXYMultiConvertible}
     * @memberof SimpleMultiDatasetAnalysis
     */
    min?: IProviderXYMultiConvertible;
    /**
     * 
     * @type {number}
     * @memberof SimpleMultiDatasetAnalysis
     */
    mean?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SimpleMultiDatasetAnalysis
     */
    readonly allDatasetsSameLength?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SimpleMultiDatasetAnalysis
     */
    readonly uniformDatasetLength?: number | null;
}

/**
 * Check if a given object implements the SimpleMultiDatasetAnalysis interface.
 */
export function instanceOfSimpleMultiDatasetAnalysis(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SimpleMultiDatasetAnalysisFromJSON(json: any): SimpleMultiDatasetAnalysis {
    return SimpleMultiDatasetAnalysisFromJSONTyped(json, false);
}

export function SimpleMultiDatasetAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleMultiDatasetAnalysis {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'max': !exists(json, 'max') ? undefined : IProviderXYMultiConvertibleFromJSON(json['max']),
        'min': !exists(json, 'min') ? undefined : IProviderXYMultiConvertibleFromJSON(json['min']),
        'mean': !exists(json, 'mean') ? undefined : json['mean'],
        'allDatasetsSameLength': !exists(json, 'allDatasetsSameLength') ? undefined : json['allDatasetsSameLength'],
        'uniformDatasetLength': !exists(json, 'uniformDatasetLength') ? undefined : json['uniformDatasetLength'],
    };
}

export function SimpleMultiDatasetAnalysisToJSON(value?: SimpleMultiDatasetAnalysis | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'max': IProviderXYMultiConvertibleToJSON(value.max),
        'min': IProviderXYMultiConvertibleToJSON(value.min),
        'mean': value.mean,
    };
}

