/* tslint:disable */
/* eslint-disable */
/**
 * ETHTPS.info API
 * Backend definition for ethtps.info; you\'re free to play around
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Network } from './Network';
import {
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
} from './Network';
import type { Provider } from './Provider';
import {
    ProviderFromJSON,
    ProviderFromJSONTyped,
    ProviderToJSON,
} from './Provider';

/**
 * 
 * @export
 * @interface TpsandGasDataMax
 */
export interface TpsandGasDataMax {
    /**
     * 
     * @type {Date}
     * @memberof TpsandGasDataMax
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof TpsandGasDataMax
     */
    maxTps?: number;
    /**
     * 
     * @type {number}
     * @memberof TpsandGasDataMax
     */
    maxGps?: number;
    /**
     * 
     * @type {number}
     * @memberof TpsandGasDataMax
     */
    maxTpsblockNumber?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TpsandGasDataMax
     */
    maxGpsblockNumber?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TpsandGasDataMax
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TpsandGasDataMax
     */
    network?: number;
    /**
     * 
     * @type {number}
     * @memberof TpsandGasDataMax
     */
    provider?: number;
    /**
     * 
     * @type {Network}
     * @memberof TpsandGasDataMax
     */
    networkNavigation?: Network;
    /**
     * 
     * @type {Provider}
     * @memberof TpsandGasDataMax
     */
    providerNavigation?: Provider;
}

/**
 * Check if a given object implements the TpsandGasDataMax interface.
 */
export function instanceOfTpsandGasDataMax(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TpsandGasDataMaxFromJSON(json: any): TpsandGasDataMax {
    return TpsandGasDataMaxFromJSONTyped(json, false);
}

export function TpsandGasDataMaxFromJSONTyped(json: any, ignoreDiscriminator: boolean): TpsandGasDataMax {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'maxTps': !exists(json, 'maxTps') ? undefined : json['maxTps'],
        'maxGps': !exists(json, 'maxGps') ? undefined : json['maxGps'],
        'maxTpsblockNumber': !exists(json, 'maxTpsblockNumber') ? undefined : json['maxTpsblockNumber'],
        'maxGpsblockNumber': !exists(json, 'maxGpsblockNumber') ? undefined : json['maxGpsblockNumber'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'network': !exists(json, 'network') ? undefined : json['network'],
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'networkNavigation': !exists(json, 'networkNavigation') ? undefined : NetworkFromJSON(json['networkNavigation']),
        'providerNavigation': !exists(json, 'providerNavigation') ? undefined : ProviderFromJSON(json['providerNavigation']),
    };
}

export function TpsandGasDataMaxToJSON(value?: TpsandGasDataMax | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'maxTps': value.maxTps,
        'maxGps': value.maxGps,
        'maxTpsblockNumber': value.maxTpsblockNumber,
        'maxGpsblockNumber': value.maxGpsblockNumber,
        'id': value.id,
        'network': value.network,
        'provider': value.provider,
        'networkNavigation': NetworkToJSON(value.networkNavigation),
        'providerNavigation': ProviderToJSON(value.providerNavigation),
    };
}

